apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: agentic-tp

resources:
  - namespace.yaml
  - postgres.yaml
  - kafka.yaml
  - discovery-server.yaml
  - auth-service.yaml
  - tp-service.yaml
  - api-gateway.yaml
  - agents.yaml
  - agent-gateway.yaml
  - frontend.yaml
